package entiteti;
// Generated Jan 9, 2019 9:33:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Artikal generated by hbm2java
 */
public class Artikal  implements java.io.Serializable {


     private Integer idartikal;
     private Korisnik korisnik;
     private String naziv;
     private int cena;
     private int kolicina;
     private int prodato;
     private Set<Stavka> stavkas = new HashSet<Stavka>(0);

    public Artikal() {
    }

	
    public Artikal(String naziv, int cena, int kolicina, int prodato) {
        this.naziv = naziv;
        this.cena = cena;
        this.kolicina = kolicina;
        this.prodato = prodato;
    }
    public Artikal(Korisnik korisnik, String naziv, int cena, int kolicina, int prodato, Set<Stavka> stavkas) {
       this.korisnik = korisnik;
       this.naziv = naziv;
       this.cena = cena;
       this.kolicina = kolicina;
       this.prodato = prodato;
       this.stavkas = stavkas;
    }
   
    public Integer getIdartikal() {
        return this.idartikal;
    }
    
    public void setIdartikal(Integer idartikal) {
        this.idartikal = idartikal;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public int getCena() {
        return this.cena;
    }
    
    public void setCena(int cena) {
        this.cena = cena;
    }
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }
    public int getProdato() {
        return this.prodato;
    }
    
    public void setProdato(int prodato) {
        this.prodato = prodato;
    }
    public Set<Stavka> getStavkas() {
        return this.stavkas;
    }
    
    public void setStavkas(Set<Stavka> stavkas) {
        this.stavkas = stavkas;
    }




}


