package entiteti;
// Generated Jan 9, 2019 9:33:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private Integer idkorisnik;
     private String username;
     private String password;
     private String tip;
     private String ime;
     private String prezime;
     private String status;
     private Set<Artikal> artikals = new HashSet<Artikal>(0);
     private Set<Porudzbina> porudzbinas = new HashSet<Porudzbina>(0);

    public Korisnik() {
    }

	
    public Korisnik(String username, String password, String tip, String ime, String prezime, String status) {
        this.username = username;
        this.password = password;
        this.tip = tip;
        this.ime = ime;
        this.prezime = prezime;
        this.status = status;
    }
    public Korisnik(String username, String password, String tip, String ime, String prezime, String status, Set<Artikal> artikals, Set<Porudzbina> porudzbinas) {
       this.username = username;
       this.password = password;
       this.tip = tip;
       this.ime = ime;
       this.prezime = prezime;
       this.status = status;
       this.artikals = artikals;
       this.porudzbinas = porudzbinas;
    }
   
    public Integer getIdkorisnik() {
        return this.idkorisnik;
    }
    
    public void setIdkorisnik(Integer idkorisnik) {
        this.idkorisnik = idkorisnik;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Artikal> getArtikals() {
        return this.artikals;
    }
    
    public void setArtikals(Set<Artikal> artikals) {
        this.artikals = artikals;
    }
    public Set<Porudzbina> getPorudzbinas() {
        return this.porudzbinas;
    }
    
    public void setPorudzbinas(Set<Porudzbina> porudzbinas) {
        this.porudzbinas = porudzbinas;
    }




}


